version: '3'

services:
  service-center:
    image: servicecomb/service-center:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    expose:
      - 30103
    ports:
      - 30103:30103
    # volumes:
    #   - "./conf/service-center/app.conf:/opt/service-center/conf/app.conf:ro"
  mongo:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: kie
      MONGO_INITDB_ROOT_USERNAME: kie
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - ./conf/mongo/db.js:/docker-entrypoint-initdb.d/db.js:ro
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kie
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_SERVER: mongo
  servicecomb-kie:
    image: servicecomb/kie:latest
    restart: always
    ports:
      - 30110:30110
    environment:
      MONGODB_USER: kie
      MONGODB_PWD: 123
      MONGODB_ADDR: mongo



